services:
  portfolio:
    image: node:20-alpine
    container_name: portfolio_v2_app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    expose:
      - "5173"
    environment:
      - VIRTUAL_HOST=porto.local
      - VIRTUAL_PORT=5173
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped
    networks:
      - default
      - proxy-net

networks:
  proxy-net:
    external: true
